# Multi-Abnormality Classification Configuration
# VLM3D Task 2: 18-class binary classification for thoracic conditions

# Data configuration
data:
  data_root: "./ct_rate_2d"  # Root directory containing extracted 2D slices
  train_csv: "./ct_rate_2d/splits/train_slices.csv"
  val_csv: "./ct_rate_2d/splits/valid_slices.csv"
  test_csv: "./ct_rate_2d/splits/test_slices.csv"  # This will be created from holdout or val split

# Model configuration
model:
  backbone: "resnet50"  # Options: resnet50, resnet101, efficientnet_b0, densenet121
  dropout_rate: 0.3
  num_classes: 18

# Training configuration
training:
  batch_size: 32
  learning_rate: 1e-4
  weight_decay: 1e-5
  max_epochs: 100
  early_stopping_patience: 15
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  
  # Loss and sampling
  use_focal_loss: true  # Better for imbalanced data
  use_weighted_sampling: true  # Sample balancing
  use_mixed_precision: true  # Memory efficiency
  
  # Hardware
  gpus: 1
  num_workers: 4
  seed: 42
  
  # Directories
  checkpoint_dir: "./checkpoints"
  log_dir: "./logs"

# Class information (18 abnormalities from CT-RATE dataset)
classes:
  - "Atelectasis"
  - "Cardiomegaly" 
  - "Consolidation"
  - "Edema"
  - "Effusion"
  - "Emphysema"
  - "Fibrosis"
  - "Fracture"
  - "Hernia"
  - "Infiltration"
  - "Mass"
  - "Nodule"
  - "Pleural_Thickening"
  - "Pneumonia"
  - "Pneumothorax"
  - "Support_Devices"
  - "Thickening"
  - "No_Finding"

# Evaluation metrics weights (for final ranking)
evaluation:
  metrics:
    auroc_weight: 0.3
    f1_weight: 0.25
    precision_weight: 0.2
    recall_weight: 0.15
    accuracy_weight: 0.1
  
  # Thresholds for binary classification
  decision_threshold: 0.5
  
  # Cross-validation settings
  cv_folds: 5
  stratified_cv: true

# Data augmentation (applied during training)
augmentation:
  rotation_degrees: 10
  horizontal_flip_prob: 0.5
  affine_translate: 0.1
  color_jitter:
    brightness: 0.2
    contrast: 0.2

# Preprocessing (applied to all data)
preprocessing:
  target_size: [224, 224]
  normalization:
    mean: [0.485, 0.456, 0.406]  # ImageNet pretrained weights
    std: [0.229, 0.224, 0.225] 