# Optimized Multi-Abnormality Classification Configuration for AUROC > 0.6
# VLM3D Task 2: Enhanced training for maximum AUROC performance

# Data configuration
data:
  data_root: "./ct_rate_2d"
  train_csv: "./ct_rate_2d/splits/train_slices.csv"
  val_csv: "./ct_rate_2d/splits/valid_slices.csv"
  test_csv: "./ct_rate_2d/splits/test_slices.csv"

# Model configuration - Optimized for AUROC
model:
  backbone: "resnet101"  # Highest capacity supported model
  dropout_rate: 0.5  # High dropout for regularization
  num_classes: 18

# Training configuration - Optimized for stability and convergence
training:
  batch_size: 12  # Smaller batches for stability
  learning_rate: 2e-5  # Very conservative learning rate
  weight_decay: 2e-4  # Strong regularization
  max_epochs: 200  # More epochs for convergence
  early_stopping_patience: 30  # More patience
  gradient_clip_val: 0.3  # Tight gradient clipping
  accumulate_grad_batches: 3  # Effective batch size = 36
  
  # Loss and sampling - Optimized for imbalanced data
  use_focal_loss: true
  use_weighted_sampling: true
  use_mixed_precision: true
  
  # Hardware
  gpus: 1
  num_workers: 4
  seed: 42
  
  # Directories
  checkpoint_dir: "./checkpoints"
  log_dir: "./logs"

# Class information (18 abnormalities from CT-RATE dataset)
classes:
  - "Atelectasis"
  - "Cardiomegaly" 
  - "Consolidation"
  - "Edema"
  - "Effusion"
  - "Emphysema"
  - "Fibrosis"
  - "Fracture"
  - "Hernia"
  - "Infiltration"
  - "Mass"
  - "Nodule"
  - "Pleural_Thickening"
  - "Pneumonia"
  - "Pneumothorax"
  - "Support_Devices"
  - "Thickening"
  - "No_Finding"

# Evaluation metrics weights - AUROC focused
evaluation:
  metrics:
    auroc_weight: 0.5  # Maximum weight on AUROC
    f1_weight: 0.2
    precision_weight: 0.1
    recall_weight: 0.15
    accuracy_weight: 0.05
  
  # Thresholds optimized for AUROC
  decision_threshold: 0.35  # Lower threshold for better sensitivity
  
  # Cross-validation settings
  cv_folds: 3  # Faster experimentation
  stratified_cv: true

# Aggressive data augmentation for better generalization
augmentation:
  rotation_degrees: 20
  horizontal_flip_prob: 0.7
  vertical_flip_prob: 0.4
  affine_translate: 0.2
  affine_scale: [0.85, 1.15]
  perspective_prob: 0.3
  color_jitter:
    brightness: 0.4
    contrast: 0.4
    saturation: 0.2
    hue: 0.1
  gaussian_noise: 0.03
  gaussian_blur_prob: 0.2
  elastic_transform: true
  grid_distortion_prob: 0.3
  coarse_dropout:
    max_holes: 8
    max_height: 16
    max_width: 16
    fill_value: 0
    prob: 0.5

# Enhanced preprocessing for CT images
preprocessing:
  target_size: [256, 256]  # Optimized input size
  normalization:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  
