# Simple but Optimized Multi-Abnormality Classification Configuration for AUROC > 0.6
# Uses only supported features from the existing codebase

# Data configuration
data:
  data_root: "./ct_rate_2d"
  train_csv: "./ct_rate_2d/splits/train_slices.csv"
  val_csv: "./ct_rate_2d/splits/valid_slices.csv"
  test_csv: "./ct_rate_2d/splits/test_slices.csv"

# Model configuration
model:
  backbone: "resnet101"  # Highest capacity supported
  dropout_rate: 0.4
  num_classes: 18

# Training configuration - Optimized for AUROC
training:
  batch_size: 8  # Small batches for stability
  learning_rate: 1e-5  # Very conservative LR
  weight_decay: 1e-4  # Strong regularization
  max_epochs: 250
  early_stopping_patience: 35
  gradient_clip_val: 0.5
  accumulate_grad_batches: 4  # Effective batch = 32
  
  # Loss and sampling
  use_focal_loss: true
  use_weighted_sampling: true
  use_mixed_precision: true
  
  # Hardware
  gpus: 1
  num_workers: 4
  seed: 42
  
  # Directories
  checkpoint_dir: "./checkpoints"
  log_dir: "./logs"

# Class information
classes:
  - "Atelectasis"
  - "Cardiomegaly" 
  - "Consolidation"
  - "Edema"
  - "Effusion"
  - "Emphysema"
  - "Fibrosis"
  - "Fracture"
  - "Hernia"
  - "Infiltration"
  - "Mass"
  - "Nodule"
  - "Pleural_Thickening"
  - "Pneumonia"
  - "Pneumothorax"
  - "Support_Devices"
  - "Thickening"
  - "No_Finding"

# Evaluation - AUROC focused
evaluation:
  metrics:
    auroc_weight: 0.5
    f1_weight: 0.2
    precision_weight: 0.1
    recall_weight: 0.15
    accuracy_weight: 0.05
  
  decision_threshold: 0.3  # Lower for better sensitivity
  cv_folds: 3
  stratified_cv: true

# Moderate augmentation
augmentation:
  rotation_degrees: 15
  horizontal_flip_prob: 0.6
  affine_translate: 0.1
  color_jitter:
    brightness: 0.3
    contrast: 0.3

# Preprocessing
preprocessing:
  target_size: [224, 224]
  normalization:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]