# Multi-Abnormality Classification Configuration
# VLM3D Task 2: 18-class binary classification for thoracic conditions

# Data configuration
data:
  data_root: "./ct_rate_2d"  # Root directory containing extracted 2D slices
  train_csv: "./ct_rate_2d/splits/train_slices.csv"
  val_csv: "./ct_rate_2d/splits/valid_slices.csv"
  test_csv: "./ct_rate_2d/splits/test_slices.csv"  # This will be created from holdout or val split

# Model configuration
model:
  backbone: "efficientnet_b2"  # Upgraded from b0 for better capacity
  dropout_rate: 0.4  # Increased dropout
  num_classes: 18

# Training configuration
training:
  batch_size: 16  # Reduced for more stable gradients
  learning_rate: 3e-5  # Lower LR for better convergence
  weight_decay: 1e-4  # Increased regularization
  max_epochs: 150
  early_stopping_patience: 25  # More patience for complex model
  gradient_clip_val: 0.5  # Tighter gradient clipping
  accumulate_grad_batches: 2  # Effective batch size = 32
  
  # Loss and sampling
  use_focal_loss: true  # Better for imbalanced data
  use_weighted_sampling: true  # Sample balancing
  use_mixed_precision: true  # Memory efficiency
  
  # Hardware
  gpus: 1
  num_workers: 4
  seed: 42
  
  # Directories
  checkpoint_dir: "./checkpoints"
  log_dir: "./logs"

# Class information (18 abnormalities from CT-RATE dataset)
classes:
  - "Atelectasis"
  - "Cardiomegaly" 
  - "Consolidation"
  - "Edema"
  - "Effusion"
  - "Emphysema"
  - "Fibrosis"
  - "Fracture"
  - "Hernia"
  - "Infiltration"
  - "Mass"
  - "Nodule"
  - "Pleural_Thickening"
  - "Pneumonia"
  - "Pneumothorax"
  - "Support_Devices"
  - "Thickening"
  - "No_Finding"

# Evaluation metrics weights (for final ranking)
evaluation:
  metrics:
    auroc_weight: 0.4  # Increased AUROC weight
    f1_weight: 0.25
    precision_weight: 0.15
    recall_weight: 0.15
    accuracy_weight: 0.05  # Reduced accuracy weight
  
  # Thresholds for binary classification
  decision_threshold: 0.4  # Lower threshold for better recall
  
  # Cross-validation settings
  cv_folds: 3  # Reduced for faster experimentation
  stratified_cv: true

# Data augmentation (applied during training)
augmentation:
  rotation_degrees: 15  # Increased rotation
  horizontal_flip_prob: 0.6  # Increased flip probability
  vertical_flip_prob: 0.3  # Add vertical flip
  affine_translate: 0.15  # Increased translation
  scale_range: [0.9, 1.1]  # Add scaling
  color_jitter:
    brightness: 0.3  # Increased brightness variation
    contrast: 0.3   # Increased contrast variation
    saturation: 0.1  # Add saturation
  gaussian_noise: 0.02  # Add noise
  elastic_transform: true  # Add elastic deformation

# Preprocessing (applied to all data)
preprocessing:
  target_size: [256, 256]  # Larger input size
  normalization:
    mean: [0.485, 0.456, 0.406]  # ImageNet pretrained weights
    std: [0.229, 0.224, 0.225]
  hu_windowing:  # CT-specific preprocessing
    min_hu: -1000
    max_hu: 400
  clahe: true  # Contrast Limited Adaptive Histogram Equalization 